CREATE TABLE staging.hmda_raw (
    stg_row_id BIGSERIAL PRIMARY KEY,
    load_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    activity_year BIGINT,
    lei TEXT,
    derived_msa_md TEXT,
    state_code TEXT,
    county_code TEXT,
    census_tract TEXT,
    conforming_loan_limit TEXT,
    derived_loan_product_type TEXT,
    derived_dwelling_category TEXT,
    derived_ethnicity TEXT,
    derived_race TEXT,
    derived_sex TEXT,
    action_taken BIGINT,
    purchaser_type TEXT,
    preapproval TEXT,
    loan_type TEXT,
    loan_purpose TEXT,
    lien_status TEXT,
    reverse_mortgage TEXT,
    open_end_line_of_credit TEXT,
    business_or_commercial_purpose TEXT,
    loan_amount DOUBLE PRECISION,
    loan_to_value_ratio TEXT,
    interest_rate TEXT,
    rate_spread TEXT,
    hoepa_status TEXT,
    total_loan_costs TEXT,
    total_points_and_fees TEXT,
    origination_charges TEXT,
    discount_points TEXT,
    lender_credits TEXT,
    loan_term TEXT,
    prepayment_penalty_term TEXT,
    intro_rate_period TEXT,
    negative_amortization TEXT,
    interest_only_payment TEXT,
    balloon_payment TEXT,
    other_nonamortizing_features TEXT,
    property_value TEXT,
    construction_method TEXT,
    occupancy_type TEXT,
    manufactured_home_secured_property_type TEXT,
    manufactured_home_land_property_interest TEXT,
    total_units TEXT,
    multifamily_affordable_units TEXT,
    income DOUBLE PRECISION,
    debt_to_income_ratio TEXT,
    applicant_credit_score_type TEXT,
    co_applicant_credit_score_type TEXT,
    applicant_ethnicity_1 TEXT,
    applicant_ethnicity_2 TEXT,
    applicant_ethnicity_3 TEXT,
    applicant_ethnicity_4 TEXT,
    applicant_ethnicity_5 TEXT,
    co_applicant_ethnicity_1 TEXT,
    co_applicant_ethnicity_2 TEXT,
    co_applicant_ethnicity_3 TEXT,
    co_applicant_ethnicity_4 TEXT,
    co_applicant_ethnicity_5 TEXT,
    applicant_ethnicity_observed TEXT,
    co_applicant_ethnicity_observed TEXT,
    applicant_race_1 TEXT,
    applicant_race_2 TEXT,
    applicant_race_3 TEXT,
    applicant_race_4 TEXT,
    applicant_race_5 TEXT,
    co_applicant_race_1 TEXT,
    co_applicant_race_2 TEXT,
    co_applicant_race_3 TEXT,
    co_applicant_race_4 TEXT,
    co_applicant_race_5 TEXT,
    co_applicant_race_observed TEXT,
    applicant_sex TEXT,
    co_applicant_sex TEXT,
    applicant_sex_observed TEXT,
    co_applicant_sex_observed TEXT,
    applicant_age TEXT,
    co_applicant_age TEXT,
    applicant_age_above_62 TEXT,
    co_applicant_age_above_62 TEXT,
    submission_of_application TEXT,
    initially_payable_to_institution TEXT,
    aus_1 TEXT,
    aus_2 TEXT,
    aus_3 TEXT,
    aus_4 TEXT,
    aus_5 TEXT,
    denial_reason_1 TEXT,
    denial_reason_2 TEXT,
    denial_reason_3 TEXT,
    denial_reason_4 TEXT,
    tract_population TEXT,
    tract_minority_population_percent TEXT,
    ffiec_msa_md_median_family_income TEXT,
    tract_to_msa_income_percentage TEXT,
    tract_owner_occupied_units TEXT,
    tract_one_to_four_family_homes TEXT,
    tract_median_age_of_housing_units TEXT,
    profile_hash CHAR(64)
);

CREATE TABLE analytics.dim_lender (
    lei_key SERIAL PRIMARY KEY,
    lei TEXT NOT NULL UNIQUE
);

CREATE TABLE analytics.dim_geography (
    geography_key SERIAL PRIMARY KEY,
    state_code TEXT NOT NULL,
    county_code TEXT NOT NULL,
    census_tract TEXT NOT NULL,
    tract_population BIGINT,
    tract_minority_population_percent DOUBLE PRECISION,
    ffiec_msa_md_median_family_income DOUBLE PRECISION,
    tract_to_msa_income_percentage DOUBLE PRECISION,
    tract_owner_occupied_units BIGINT,
    tract_one_to_four_family_homes BIGINT,
    tract_median_age_of_housing_units INTEGER,
    UNIQUE (state_code, county_code, census_tract)
);

CREATE TABLE analytics.dim_loan (
    loan_key SERIAL PRIMARY KEY,
    loan_type TEXT NOT NULL,
    loan_purpose TEXT NOT NULL,
    lien_status TEXT NOT NULL,
    reverse_mortgage TEXT,
    open_end_line_of_credit TEXT,
    business_or_commercial_purpose TEXT,
    conforming_loan_limit TEXT,
    UNIQUE NULLS NOT DISTINCT (loan_type, loan_purpose, lien_status, reverse_mortgage, open_end_line_of_credit, business_or_commercial_purpose, conforming_loan_limit)
);

CREATE TABLE analytics.dim_applicant_profile (
    applicant_profile_key SERIAL PRIMARY KEY,
    applicant_ethnicity_1 TEXT,
    applicant_ethnicity_2 TEXT,
    applicant_ethnicity_3 TEXT,
    applicant_ethnicity_4 TEXT,
    applicant_ethnicity_5 TEXT,
    applicant_ethnicity_observed TEXT,
    co_applicant_ethnicity_1 TEXT,
    co_applicant_ethnicity_2 TEXT,
    co_applicant_ethnicity_3 TEXT,
    co_applicant_ethnicity_4 TEXT,
    co_applicant_ethnicity_5 TEXT,
    co_applicant_ethnicity_observed TEXT,
    applicant_race_1 TEXT,
    applicant_race_2 TEXT,
    applicant_race_3 TEXT,
    applicant_race_4 TEXT,
    applicant_race_5 TEXT,
    co_applicant_race_1 TEXT,
    co_applicant_race_2 TEXT,
    co_applicant_race_3 TEXT,
    co_applicant_race_4 TEXT,
    co_applicant_race_5 TEXT,
    co_applicant_race_observed TEXT,
    applicant_sex TEXT,
    co_applicant_sex TEXT,
    applicant_sex_observed TEXT,
    co_applicant_sex_observed TEXT,
    applicant_age TEXT,
    co_applicant_age TEXT,
    applicant_age_above_62 TEXT,
    co_applicant_age_above_62 TEXT,
    applicant_credit_score_type TEXT,
    co_applicant_credit_score_type TEXT,
    profile_hash CHAR(64) NOT NULL UNIQUE
);

CREATE TABLE analytics.dim_action_taken (
    action_taken_key SERIAL PRIMARY KEY,
    action_taken INTEGER NOT NULL UNIQUE
);

CREATE TABLE analytics.fact_loan_application (
    fact_loan_application_key SERIAL PRIMARY KEY,
    lei_key INTEGER NOT NULL REFERENCES analytics.dim_lender(lei_key),
    geography_key INTEGER NOT NULL REFERENCES analytics.dim_geography(geography_key),
    loan_key INTEGER NOT NULL REFERENCES analytics.dim_loan(loan_key),
    applicant_profile_key INTEGER NOT NULL REFERENCES analytics.dim_applicant_profile(applicant_profile_key),
    action_taken_key INTEGER NOT NULL REFERENCES analytics.dim_action_taken(action_taken_key),
    loan_amount DOUBLE PRECISION,
    income DOUBLE PRECISION,
    application_year BIGINT,
    load_timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    source_row_id BIGINT NOT NULL
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_fact_lei ON analytics.fact_loan_application(lei_key);
CREATE INDEX IF NOT EXISTS idx_fact_geography ON analytics.fact_loan_application(geography_key);
CREATE INDEX IF NOT EXISTS idx_fact_loan ON analytics.fact_loan_application(loan_key);
CREATE INDEX IF NOT EXISTS idx_fact_applicant ON analytics.fact_loan_application(applicant_profile_key);
CREATE INDEX IF NOT EXISTS idx_fact_action ON analytics.fact_loan_application(action_taken_key);
CREATE INDEX IF NOT EXISTS idx_fact_year ON analytics.fact_loan_application(application_year);